
#- name: need to install tomcat
#  include: install-tomat.yml


- name: check dir is exists, if not, mkdir it
  file:
    path: "{{xwiki_download_dir}}"
    state: directory

- name: download xwiki war
  get_url:
    url: "{{xwiki_download_url}}"
    dest: "{{xwiki_download_dir}}/{{xwiki_war}}"

- name: copy xwiki.war to tomcat
  copy:
    src: "{{xwiki_download_dir}}/{{xwiki_war}}"
    dest: "{{xwiki_tomcat_app_dir}}/{{xwiki_tomcat_war_name}}"
    remote_src: yes
    owner: tomcat
    group: tomcat
    mode: 0777

- name: unzip xwiki.war
  shell: "cd {{xwiki_tomcat_app_dir}} && unzip -f ./{{xwiki_tomcat_war_name}} -d {{xwiki_tomcat_run_name}}  "
  with_items:
    - unzip
    - zip

- name: copy xwiki config
  template:
    src: xwiki.cfg.j2
    dest: "{{xwiki_tomcat_app_dir}}/{{xwiki_tomcat_run_name}}/WEB-INF/xwifi.cfg"
    owner: tomcat
    group: tomcat
    mode: 0777

- name: check db is ok?
  debug:
    msg: use hsqldb, if you want to use mysql or other, please copy db diriver and change hibernate.cfg.xml

- name: copy hsqldb driver to xwiki
  copy:
    src: hsqldb.jar
    dest: "{{xwiki_tomcat_app_dir}}/{{xwiki_tomcat_run_name}}/WEB-INF/lib"
    owner: tomcat
    group: tomcat
    mode: 0777

- name: check tomcat is started
  shell: "ps -ef|grep {{xwiki_tomcat_app_dir}}"
  register: tomcat_not_start || false

#- name: tomcat state
#  debug:
#    msg: "{{tomcat_not_start}}"

- name: start tomcat if not started
  shell: "cd {{xwiki_tomcat_app_dir}} && cd ../ && ./bin/startup.sh"
  when: true